### PR TITLE
chore: replace Radix with Superlinear

### PR DESCRIPTION
**Pull request by sinopeus**

### CODE REVIEW

**Comment by sinopeus** [comment]
[This line](https://github.com/superlinear-ai/poetry-cookiecutter/blob/08c7fcd740fc0807e7de1810950c40fc4ac93013/.github/workflows/test.yml#L35) tells us we still need to rename our Docker image.

**Comment by lsorber** [comment]
> [This line](https://github.com/superlinear-ai/poetry-cookiecutter/blob/08c7fcd740fc0807e7de1810950c40fc4ac93013/.github/workflows/test.yml#L35) tells us we still need to rename our Docker image.

@sinopeus We now have Superlinear images: https://hub.docker.com/r/superlinear/python-gpu. Could you continue with this PR so we can complete the name change? Thank you!

**Comment by sinopeus** [comment]
> > [This line](https://github.com/superlinear-ai/poetry-cookiecutter/blob/08c7fcd740fc0807e7de1810950c40fc4ac93013/.github/workflows/test.yml#L35) tells us we still need to rename our Docker image.
> 
> @sinopeus We now have Superlinear images: https://hub.docker.com/r/superlinear/python-gpu. Could you continue with this PR so we can complete the name change? Thank you!

Done!

**Review by lsorber — APPROVED** [review]
LGTM!

**Pull request merged**
